#!/bin/bash

#sed -i '1{G;s/$/export CATALINA_OPTS="$CATALINA_OPTS -server -Xms\${JVM_ARG_XMS} -Xmx\${JVM_ARG_XMX} -Xss\${JVM_ARG_XSS}"/}' $CATALINA_HOME/bin/catalina.sh
export CATALINA_OPTS="$CATALINA_OPTS -server -Xms${JVM_ARG_XMS} -Xmx${JVM_ARG_XMX} -Xss${JVM_ARG_XSS}"

if [ -z "`grep \"modified by docker\" $CATALINA_HOME/conf/server.xml`" ];
then
sed -i "s|<Connector port=\"8080\" protocol=\"HTTP/1.1\"|<!-- modified by docker--><Connector port=\"8080\" protocol=\"HTTP/1.1\" minSpareThreads=\"${MIN_SPARE_THREADS}\" maxThreads=\"${MAX_THREADS}\" acceptCount=\"${ACCEPT_COUNT}\" maxConnections=\"${MAX_CONNECTIONS}\"|g"  $CATALINA_HOME/conf/server.xml
fi


if [ "true" = "$JPDA_START" ]; then
  echo "Starting Tomcat JPDA Mode (${JPDA_TRANSPORT}:${JPDA_ADDRESS}) ..."
  export CATALINA_OPTS="${CATALINA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,address=${JPDA_ADDRESS},server=y,suspend=n"
  export CATALINA_OPTS="${CATALINA_OPTS} -Dcom.sun.management.jmxremote "
  export CATALINA_OPTS="${CATALINA_OPTS} -Dcom.sun.management.jmxremote.local.only=false"
  if [ ! -z "$JAVA_RMI_SERVER_HOSTNAME" ]; then
    #In Mesos env JAVA_RMI_SERVER_HOSTNAME should be the docker service hostname
    export CATALINA_OPTS="${CATALINA_OPTS} -Djava.rmi.server.hostname='${JAVA_RMI_SERVER_HOSTNAME}'"
  #else
  #  export CATALINA_OPTS="${CATALINA_OPTS} -Djava.rmi.server.hostname=${HOSTNAME}"
  fi
  export CATALINA_OPTS="${CATALINA_OPTS} -Dcom.sun.management.jmxremote.port=${JMX_PORT} -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} "
  export CATALINA_OPTS="${CATALINA_OPTS} -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"

  export JPDA_OPTS="$JAVA_OPTS"
  /bin/sh -c "$CATALINA_HOME/bin/catalina.sh jpda start"
else
  echo "Starting Tomcat ..."
  /bin/sh -c "$CATALINA_HOME/bin/catalina.sh run"
fi
